# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_scrapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
