# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_emart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emart',
            name='price',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='emart',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
