# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_handling2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handling3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=300)),
                ('min_order1', models.CharField(blank=True, max_length=300)),
                ('title2', models.CharField(max_length=300)),
                ('min_order2', models.CharField(blank=True, max_length=300)),
                ('title3', models.CharField(max_length=300)),
                ('min_order3', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
