# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170703_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emart',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
