# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170725_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lngat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
