# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='rice',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='tissue',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='water',
            field=models.BooleanField(),
        ),
    ]
