# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='memo',
            field=models.TextField(),
        ),
    ]
