# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170728_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
